version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: agriakutest
      POSTGRES_PASSWORD: agriakutest123
      POSTGRES_DB: agriakutestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.3
    container_name: airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://agriakutest:agriakutest123@postgres:5432/agriakutestdb
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/agriaku-data-engineer-test/data
      - ./output:/agriaku-data-engineer-test/output
      - ./processed_files:/agriaku-data-engineer-test/processed_files
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com &&
        airflow scheduler & airflow webserver"
    restart: always

volumes:
  postgres_data:
